CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role ENUM('NASABAH', 'ADMIN', 'TELLER', 'MANAGER') DEFAULT 'NASABAH',
    tier ENUM('REGULER', 'GOLD', 'PRIORITAS') DEFAULT 'REGULER',
    balance DECIMAL(15, 2) DEFAULT 0.00,
    loan DECIMAL(15, 2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transactions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    refId VARCHAR(100) NOT NULL UNIQUE,
    type VARCHAR(50) NOT NULL,
    fromUserId VARCHAR(50) NOT NULL,
    toUserId VARCHAR(50) NOT NULL,
    baseAmount DECIMAL(15, 2) NOT NULL,
    tax DECIMAL(15, 2) DEFAULT 0.00,
    fee DECIMAL(15, 2) DEFAULT 0.00,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS loans (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId VARCHAR(50) NOT NULL,
    amount DECIMAL(15, 2) NOT NULL,
    interestRate DECIMAL(5, 4) DEFAULT 0.1000,
    totalDue DECIMAL(15, 2) NOT NULL,
    status ENUM('PENDING', 'APPROVED', 'PAID', 'REJECTED') DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
